---
  - name: Installing ranger (apt package)
    hosts: ubuntu 
    become: true
    tasks:
    - name: Installing ranger
      apt:
        name: ranger

  - name: Installing apache (yum package)
    hosts: centos
    become: true
    tasks:
    - name: Installing apache
      yum: 
        name: httpd
        state: latest
  
  - name: Creating a new linux user
    hosts: centos
    become: true
    tasks: 
      - name: Create a user
        become: true 
        user: 
          name: samnick
          shell: /bin/bash
      - name: Unlock the password
        become: true
        command: echo "password" | passwd samnick -e

        
  - name: Create a domain user
    hosts: dc
    tasks: 
      - name: Create a user
        win_domain_user:
          name: samnick
          firstname: samnick
          surname: samnick
          password: Userpassword$123
          state: present
          domain_username: GROUP3.LOCAL\group3adm
          domain_password: Userpassword$123
          domain_server: GROUP3.LOCAL
